// Generated by json_to_model

#import <Foundation/Foundation.h>
#import "Profile.h"


@interface Configuration : NSObject

- (id)initWithJSONData:(NSData *)data;
- (id)initWithJSONDictionary:(NSDictionary *)dictionary;
- (id)clearConfigs;
- (id)setConfigs:(NSArray*)configs;
- (NSDictionary *)JSONDictionary;
- (NSData *)JSONData;
- (BOOL) hasConfigs;


@property (nonatomic, assign) NSInteger current;

@property (nonatomic, strong) NSArray * profiles;


@end

